In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [86]:
#reading the file
data=pd.read_csv('Placement_Data_Full_Class.csv - Sheet1.csv')
data

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
5        6      M  55.00   Others  49.80   Others   Science     67.25   
6        7      F  46.00   Others  49.20   Others  Commerce     79.00   
7        8      M  82.00  Central  64.00  Central   Science     66.00   
8        9      M  73.00  Central  79.00  Central  Commerce     72.00   
9       10      M  58.00  Central  70.00  Central  Commerce     61.00   
10      11      M  58.00  Central  61.00  Central  Commerce     60.00   
11      12      M  69.60  Central  68.40  Central  Commerce     78.30   
12      13      F  47.00  Central  55.00   Others   Science     65.00   
13      14      F  77.00  Central  87.00  Central  Commerce     59.00   
14      15      M  62.00  Central  47.00  Central  Commerce     50.00   
15      16      F  65.00  Central  75.00  Central  Commerce     69.00   
16      17      M  63.00  Central  66.20  Central  Commerce     65.60   
17      18      F  55.00  Central  67.00  Central  Commerce     64.00   
18      19      F  63.00  Central  66.00  Central  Commerce     64.00   
19      20      M  60.00   Others  67.00   Others      Arts     70.00   
20      21      M  62.00   Others  65.00   Others  Commerce     66.00   
21      22      F  79.00   Others  76.00   Others  Commerce     85.00   
22      23      F  69.80   Others  60.80   Others   Science     72.23   
23      24      F  77.40   Others  60.00   Others   Science     64.74   
24      25      M  76.50   Others  97.70   Others   Science     78.86   
25      26      F  52.58   Others  54.60  Central  Commerce     50.20   
26      27      M  71.00   Others  79.00   Others  Commerce     66.00   
27      28      M  63.00   Others  67.00   Others  Commerce     66.00   
28      29      M  76.76   Others  76.50   Others  Commerce     67.50   
29      30      M  62.00  Central  67.00  Central  Commerce     58.00   
..     ...    ...    ...      ...    ...      ...       ...       ...   
185    186      F  88.00  Central  72.00  Central   Science     78.00   
186    187      F  52.00  Central  64.00  Central  Commerce     61.00   
187    188      M  78.50  Central  65.50  Central   Science     67.00   
188    189      M  61.80   Others  47.00   Others  Commerce     54.38   
189    190      F  54.00  Central  77.60   Others  Commerce     69.20   
190    191      F  64.00   Others  70.20  Central  Commerce     61.00   
191    192      M  67.00   Others  61.00  Central   Science     72.00   
192    193      M  65.20  Central  61.40  Central  Commerce     64.80   
193    194      F  60.00  Central  63.00  Central      Arts     56.00   
194    195      M  52.00   Others  55.00   Others  Commerce     56.30   
195    196      M  66.00  Central  76.00  Central  Commerce     72.00   
196    197      M  72.00   Others  63.00   Others   Science     77.50   
197    198      F  83.96   Others  53.00   Others   Science     91.00   
198    199      F  67.00  Central  70.00  Central  Commerce     65.00   
199    200      M  69.00   Others  65.00   Others  Commerce     57.00   
200    201      M  69.00   Others  60.00   Others  Commerce     65.00   
201    202      M  54.20  Central  63.00   Others   Science     58.00   
202    203      M  70.00  Central  63.00  Central   Science     66.00   
203    204      M  55.68   Others  61.33   Others  Commerce     56.87   
204    205      F  74.00   Others  73.00   Others  Commerce     73.00   
205    206      M  61.00   Others  62.00   Others  Commerce     65.00   
206    207      M  41.00  Central  42.00  Central   Science     60.00   
207    208      M  83.33  Central  78.00   Others  Commerce    

In [87]:
#droping the serial no and salary col
data=data.drop('sl_no',axis=1)
data=data.drop('salary',axis=1)
data.head()


gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p   degree_t  \
0      M  67.00   Others  91.00   Others  Commerce     58.00   Sci&Tech   
1      M  79.33  Central  78.33   Others   Science     77.48   Sci&Tech   
2      M  65.00  Central  68.00  Central      Arts     64.00  Comm&Mgmt   
3      M  56.00  Central  52.00  Central   Science     52.00   Sci&Tech   
4      M  85.80  Central  73.60  Central  Commerce     73.30  Comm&Mgmt   

  workex  etest_p specialisation  mba_p      status  
0     No     55.0         Mkt&HR  58.80      Placed  
1    Yes     86.5        Mkt&Fin  66.28      Placed  
2     No     75.0        Mkt&Fin  57.80      Placed  
3     No     66.0         Mkt&HR  59.43  Not Placed  
4     No     96.8        Mkt&Fin  55.50      Placed

In [88]:
# for i in range(0,215):
#     if(data['gender'][i]=='M'):
#         data['gender'][i]=1
#     else:
#         data['gender'][i]=0


#catgorising col for further labelling
data["gender"]=data["gender"].astype('category')
data["ssc_b"]=data["ssc_b"].astype('category')
data["hsc_b"]=data["hsc_b"].astype('category')
data["degree_t"]=data["degree_t"].astype('category')
data["workex"]=data["workex"].astype('category')
data["specialisation"]=data["specialisation"].astype('category')
data["status"]=data["status"].astype('category')
data["hsc_s"]=data["hsc_s"].astype('category')
data.dtypes

gender            category
ssc_p              float64
ssc_b             category
hsc_p              float64
hsc_b             category
hsc_s             category
degree_p           float64
degree_t          category
workex            category
etest_p            float64
specialisation    category
mba_p              float64
status            category
dtype: object

In [89]:
#labelling the col
data["gender"]=data["gender"].cat.codes
data["ssc_b"]=data["ssc_b"].cat.codes
data["hsc_b"]=data["hsc_b"].cat.codes
data["degree_t"]=data["degree_t"].cat.codes
data["workex"]=data["workex"].cat.codes
data["specialisation"]=data["specialisation"].cat.codes
data["status"]=data["status"].cat.codes
data["hsc_s"]=data["hsc_s"].cat.codes
data

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0         1  67.00      1  91.00      1      1     58.00         2       0   
1         1  79.33      0  78.33      1      2     77.48         2       1   
2         1  65.00      0  68.00      0      0     64.00         0       0   
3         1  56.00      0  52.00      0      2     52.00         2       0   
4         1  85.80      0  73.60      0      1     73.30         0       0   
5         1  55.00      1  49.80      1      2     67.25         2       1   
6         0  46.00      1  49.20      1      1     79.00         0       0   
7         1  82.00      0  64.00      0      2     66.00         2       1   
8         1  73.00      0  79.00      0      1     72.00         0       0   
9         1  58.00      0  70.00      0      1     61.00         0       0   
10        1  58.00      0  61.00      0      1     60.00         0       1   
11        1  69.60      0  68.40      0      1     78.30         0       1   
12        0  47.00      0  55.00      1      2     65.00         0       0   
13        0  77.00      0  87.00      0      1     59.00         0       0   
14        1  62.00      0  47.00      0      1     50.00         0       0   
15        0  65.00      0  75.00      0      1     69.00         0       1   
16        1  63.00      0  66.20      0      1     65.60         0       1   
17        0  55.00      0  67.00      0      1     64.00         0       0   
18        0  63.00      0  66.00      0      1     64.00         0       0   
19        1  60.00      1  67.00      1      0     70.00         0       1   
20        1  62.00      1  65.00      1      1     66.00         0       0   
21        0  79.00      1  76.00      1      1     85.00         0       0   
22        0  69.80      1  60.80      1      2     72.23         2       0   
23        0  77.40      1  60.00      1      2     64.74         2       1   
24        1  76.50      1  97.70      1      2     78.86         2       0   
25        0  52.58      1  54.60      0      1     50.20         0       1   
26        1  71.00      1  79.00      1      1     66.00         0       1   
27        1  63.00      1  67.00      1      1     66.00         0       0   
28        1  76.76      1  76.50      1      1     67.50         0       1   
29        1  62.00      0  67.00      0      1     58.00         0       0   
..      ...    ...    ...    ...    ...    ...       ...       ...     ...   
185       0  88.00      0  72.00      0      2     78.00         1       0   
186       0  52.00      0  64.00      0      1     61.00         0       0   
187       1  78.50      0  65.50      0      2     67.00         2       1   
188       1  61.80      1  47.00      1      1     54.38         0       0   
189       0  54.00      0  77.60      1      1     69.20         0       0   
190       0  64.00      1  70.20      0      1     61.00         0       0   
191       1  67.00      1  61.00      0      2     72.00         0       0   
192       1  65.20      0  61.40      0      1     64.80         0       1   
193       0  60.00      0  63.00      0      0     56.00         1       1   
194       1  52.00      1  55.00      1      1     56.30         0       0   
195       1  66.00      0  76.00      0      1     72.00         0       1   
196       1  72.00      1  63.00      1      2     77.50         2       1   
197       0  83.96      1  53.00      1      2     91.00         2       0   
198       0  67.00      0  70.00      0      1     65.00         1       0   
199       1  69.00      1  65.00      1      1     57.00         0       0   
200       1  69.00      1  60.00      1      1     65.00         0       0   
201       1  54.20      0  63.00      1      2     58.00         0       0   
202       1  70.00      0  63.00      0      2     66.00         2       0   
203       1  55.68      1  61.33      1      1     56.87         0       0   
204       0  74.00      1  

In [90]:
#selecting the features and labels
X=data.iloc[:,:-1].values
Y=data.iloc[:,-1].values
Y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int8)

In [91]:
#dividing the data into train and split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
X_train
data.head()

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0       1  67.00      1  91.00      1      1     58.00         2       0   
1       1  79.33      0  78.33      1      2     77.48         2       1   
2       1  65.00      0  68.00      0      0     64.00         0       0   
3       1  56.00      0  52.00      0      2     52.00         2       0   
4       1  85.80      0  73.60      0      1     73.30         0       0   

   etest_p  specialisation  mba_p  status  
0     55.0               1  58.80       1  
1     86.5               0  66.28       1  
2     75.0               0  57.80       1  
3     66.0               1  59.43       0  
4     96.8               0  55.50       1

In [92]:
#creating a classifier using sklearn
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train,Y_train)
#printing the acc
clf.score(X_test,Y_test)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9534883720930233

In [93]:
#predicting for random value
clf.predict([[1,77,0,95,0,2,80,2,0,0,1,0]])

array([1], dtype=int8)

In [94]:
#creating a Y_pred for test data
Y_pred=clf.predict(X_test)
Y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1],
      dtype=int8)

In [95]:
#evalution of the classifier
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)


[[ 9  2]
 [ 0 32]]


0.9534883720930233